### ISSUE TITLE
Import jtsCalibration and jtsCalibrationGUI in the codyco-superbuild

### ISSUE THREAD

**Issue by traversaro** [ocra-recipes/ocra-wbi-plugins#1]
I guess that for simplifying software maintenance we should integrate the joint torque calibration modules [1] [2] developed by @ghamon88 in the codyco-superbuild . 

There are two ways of doing it: 
- Add them to an existing repository (for example codyco-isir)
- Add them as independent repositories

I would go for the first option, because for each subproject added to the superbuild there is a fixed overhead related to each to the checkout/update time. 

cc @rlober @darwinlau @vpadois 

[1] : https://github.com/ghamon88/jtsCalibration
[2] : https://github.com/ghamon88/jtsCalibrationGUI

**Comment by rlober** [comment]
Hey @traversaro 

Sorry no one ever replied to this... I havn't tried this software out yet but maybe we can integrate it in the near future. We may be dedicating some more resources on our end to this project in the near future ( @ahoarau  ), but right now it is on the back burners. It would be nice to package this up with the [pidTuner](https://github.com/rlober/pidTuner) project and maybe expand the scope to include an automated parameter identification tool...? Sounds like a lot of work to me but it could be very useful. Are you guys working on anything like this at IIT?

**Comment by traversaro** [comment]
Hey I had totally forgot about this!

**Comment by rlober** [comment]
@traversaro 

I am going to close this issue here and try to move the jts code to an isir based organization and integrate them with superbuild over time. This could become part of the pidTuner project but I think we may reconsider the scope and work together with IIT to make a real tool.

EDIT:

Moved to robotology-playground:
https://github.com/robotology-playground/jtsCalibration
https://github.com/robotology-playground/jtsCalibrationGUI

**Comment by traversaro** [comment]
Integrating this kind of tools in pidTuner would be a great idea.

**Comment by rlober** [comment]
@traversaro 

What I would like to do around February is sit down with you and Dany and Ugo and discuss the possibility of a real tool and not just my crappy pidTuner. I am thinking this could be an all around joint/model identification tool. Also @DanielePucci, I have some ideas on how to directly use viscous friction for the damping temp on the torque control.

**Comment by DanielePucci** [comment]
Deal!
