### ISSUE TITLE
Add clang to travis build.

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-wbi-plugins#4]
@ahoarau 

Help me obi wan kenobi you're my only hope!

cc @traversaro

**Comment by traversaro** [comment]
A trick that I use for the project with a lot of dependencies is to use the superbuild to download/build the dependencies, see https://github.com/robotology/codyco-modules/blob/master/.travis.yml .

**Comment by rlober** [comment]
@ahoarau status?

**Comment by ahoarau** [comment]
Done ! And osx as well

**Comment by rlober** [comment]
:+1:
